require: 
  - rubocop-performance
  - rubocop-rails

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - '**/vendor/**/*'
    - app/views/**/*
    - config/**/*
    - config.ru
    - node_modules/**/*
    - db/migrate/*
    - db/schema.rb
    - storage/**/*
    - tmp/**/*
    - bin/**/*
